#!/usr/bin/env ruby

target_dir = ARGV.shift || '/home/jeff/Dropbox/docs/wiki/'
ARGV.clear

rails_pid = fork do
  Dir.chdir "rails"
  `NOTES_DIR=#{target_dir} rails s -p 4000`
end

`cd ui && yarn start`
gets

Process.kill 9, rails_pid
